const data =[
    {
        id:0,
        title: 'Room 1',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images1.jpeg',
        stars: 4.8,
        type: 'Budget Room',
        stars: 3.8,
        bed: 1,
        shower: 1,
        price: 110,
    },
    {
        id:1,
        title: 'Room 2',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images2.jpeg',
        stars: 3.8,
        type: 'Budget Room',
        stars: 3.9,
        bed: 1,
        shower: 1,
        price: 110,
    },
    {
        id:2,
        title: 'Room 2',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images3.jpeg',
        stars: 4.1,
        type: "Premium Room",
        stars: 4.9,
        bed: 1,
        shower: 1,
        ac: 1,
        price: 230,
    },
    {
        id:3,
        title: 'Room 3',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images4.jpeg',
        stars: 3.3,
        type: 'Deluxe Room',
        stars: 4.9,
        bed: 2,
        shower: 1,
        ac: 1,
        price: 190,
    },
    {
        id:4,
        title: 'Room 4',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images5.jpeg',
        stars: 4.8,
        type: "Captain's Suite",
        stars: 4.9,
        bed: 2,
        shower: 1,
        ac: 1,
        price: 320,
        wifi: true

    },
    {
        id:5,
        title: 'Room 5',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images6.jpeg',
        stars: 4.9,
        type: 'Penthouse Suite',
        stars: 4.9,
        bed: 2,
        shower: 2,
        ac: 1,
        price: 360,
        wifi: true
    },
    {
        id:6,
        title: 'Room 6',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images7.jpeg',
        type: 'Penthouse Suite',
        stars: 4.9,
        bed: 2,
        shower: 2,
        ac: 1,
        price: 360,
        wifi: true
    },
    {
        id:7,
        title: 'Room 7',
        descrition: 'Lorem Isum dolor sit amet',
        img: './assets/images/images9.jpeg',
        stars: 4.4,
        type: 'Penthouse Suite',
        bed: 2,
        shower: 2,
        ac: 1,
        wifi: true,
        price: 360,
    },
]

export default data;